# Lang
language: en

# Dark Mode
dark: false

# Header
menu:
  Home: /
  Archives: /archives
  About: /about

# Your Feed Location
#rss: /atom.xml

# Content
fancybox: true


# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter: https://twitter.com/fexnotes
google_plus:
fb_admins:
fb_app_id:


# Profile
nickname: fexnotes
description: I am a web developer, mybe like you. I record my thought & views here,You can share yours via comments or [email](mailto:rockcoder@126.com)


# Load fontawesome icons? Also see the links option
icons: false

# Footer area links
# NOTICE) If you set "icons: false" link names will be clear text
# If "icons: true" link names will interpreted as fontawesome icon names
# NOTICE) Use the fontawesome icon names without the fa- prefix (http://fontawesome.io/cheatsheet/)
links:
  Blog: /archives/
  Twitter: https://twitter.com/fexnotes
  Github: https://github.com/rockcoder23
  About: /about/

# nav position (top, left. top is default)
nav: left

# Info
archive_footer_content: Lorem ipsum dolor sit amet, **consectetur adipiscing elit.** Fusce eget urna vitae velit *eleifend interdum at ac nisi. In nec ligula lacus. Cum sociis natoque* penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed eu cursus erat, ut dapibus quam. Archive
post_footer_content: ipsum dolor sit amet, **consectetur adipiscing elit.** Fusce eget urna vitae velit *eleifend interdum at ac nisi. In nec ligula lacus. Cum sociis natoque* penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed eu cursus erat, ut dapibus quam. Post

# Utterances
# NOTICE) make sure the app is installed on the repo before using this commit system
# see https://utteranc.es/ for more
utterances:
  enable: true
  repo: rockcoder23/blog.fexnotes.com # your repo in this format: 'username/reponame', note that there is no '.git' suffix

# Donate
donate:
  enable: false
  github: https://github.com/geekplux
  paypal: https://www.paypal.me/geekplux
  bitcoin: 1AVngxh56oLvAzXsEFnzccUohZdHswjC7j
  BTCQR: http://7b1evr.com1.z0.glb.clouddn.com/donate/bitcoin.png
  AliPayQR: http://7b1evr.com1.z0.glb.clouddn.com/donate/alipayQR.jpg
  WeChatQR: http://7b1evr.com1.z0.glb.clouddn.com/donate/wechatQR.jpg
